### ISSUE TITLE
Where to find available offering types to create cases?

### ISSUE THREAD

**Issue by malomehi** [IBM/platform-services-python-sdk#111]
Hi,

Are all the available offering types that can be used to create a case documented somewhere?

I found an example here for `Cloud Object Storage`: https://cloud.ibm.com/apidocs/case-management?code=python#createcase

Where can I find the `group`, `key` and `name` for the rest of available offering types?

Thanks.

**Comment by padamstx** [comment]
I belive this was answered via slack.  If not, please re-open.
