### ISSUE TITLE
ibm-platform-services is not compatible with ibm-cos-sdk-config which is >1.1.0 version.

### ISSUE THREAD

**Issue by lokeshdubeyin** [IBM/platform-services-python-sdk#132]
**Describe the bug**
ibm-platform-services is not compatible with ibm-cos-sdk-config which is >1.1.0 version. (any version of ibm-platform-services)

**To Reproduce**
pip install --upgrade ibm-platform-services  ibm-cos-sdk-config
This always installs ibm-cos-sdk-config 1.1.0. Which is a pretty old version and conflicts with actual cos sdk usages and produces errors like :

    b_size, b_num = getBucketSize(b)
  File "/code/cosGetBuckets.py", line 25, in getBucketSize
    client = ResourceConfigurationV1(iam_apikey=os.environ["CLOUD_API_KEY"])
  File "/usr/local/lib/python3.7/site-packages/cos_config/resource_configuration_v1.py", line 79, in __init__
    display_name='ResourceConfiguration')
TypeError: __init__() got an unexpected keyword argument 'vcap_services_name'

List the steps that can be used to demonstrate the bug.  Include the name of the service and operation that you're trying to invoke, if applicable.  Be sure to describe any relevant info regarding parameter values used with your API invocation.

**Expected behavior**
As I need to use platform services for getting billing information from Cloud account and ibm cos sdk to get bucketsize as well. Even if I let pip decide for apporpirate versions together it eventually goes down to 1.1.0 level

**Screenshots**

**Must gather (please complete the following information):**
 - Python Version 3.7

**Comment by Andras-Csanyi** [comment]
Hi @lokeshdubeyin,

Thanks for letting us know about this issue. Let us take a look at it and get back to you!
Thank you!

**Comment by Andras-Csanyi** [comment]
@lokeshdubeyin 
I believe the root of the issue is that the two package requires different version from `ibm_cloud_sdk_core`. `ibm-platform-services` requires [ibm_cloud_sdk_core>=3.11.3,<4.0.0](https://github.com/IBM/platform-services-python-sdk/blob/main/requirements.txt) while `ibm-cos-sdk-config` requires [ibm-cloud-sdk-core>=0.5.3,<1.0.0]{https://github.com/IBM/ibm-cos-sdk-python-config/blob/master/requirements.txt}.

What versions do you have installed in your project?

**Comment by Andras-Csanyi** [comment]
@lokeshdubeyin 
We had a chat with the COS team about this issue and there will be a release which resolves this issue in the future. Unfortunately no solid timeline or date for this yet. I opened an [issue](https://github.com/IBM/ibm-cos-sdk-python-config/issues/1) in the COS team repo so they are aware of your issue and they might can help you to find a workaround until the new release comes out.

**Comment by lokeshdubeyin** [comment]
Thanks @Andras-Csanyi for letting us know. I'll be on the look out for this.
