### ISSUE TITLE
How to calculate cost of Virtual Server Instance from Global Catalog API

### ISSUE THREAD

**Issue by xdevapps** [IBM/platform-services-python-sdk#153]
I am trying to estimate costs for Virtual Server Instances on VPC for various configurations/profiles available on IBM Cloud gen2. I found that the Global Catalog API can be used to get pricing plans for various resources. Using this I was able to retrieve prices for the 'advanced-vsi' pricing plan under the 'is.instance' resource. This returned me a dict of metrics and their prices in different currencies.
An example of the metric data is as shown:
```json
{
  "metrics": [
    {
      "part_ref": "",
      "metric_id": "part-is.cpu-hours",
      "tier_model": "Linear Tier",
      "resource_display_name": "VCPU_HOURS",
      "charge_unit_display_name": "vCPU-Hours",
      "charge_unit_name": "VCPU_HOURS",
      "charge_unit": "Virtual Processor Core-Hour",
      "charge_unit_quantity": 63,
      "amounts": [
        {
          "country": "USA",
          "currency": "USD",
          "prices": [
            {
              "quantity_tier": 1,
              "price": 1.67
            }
          ]
        }
      ],
      "usage_cap_qty": 0,
      "display_cap": 0,
      "effective_from": "2022-02-01T00:00:00Z",
      "effective_until": "9999-12-30T16:00:00Z"
    },
  ]
}
```
I tried using this data to estimate cost for VCPU usage per hour, but the results of my calculations do not match those of the IBM cost estimator or even of the monthly usage billing data.
My calculation:
```python3
cost_per_hour = num_vcpus * vcpu_metric['amounts'][0]['prices'][0] / vcpu_metric['amounts'][0]['charge_unit_quantity']
```

Is there something wrong with my logic? Please help me find a proper mapping between the values returned by the API and the estimated costs for the VSIs.

P.S Since this repo provides a wrapper over the Global Catalog API, I considered asking my question here. If this is not the right place for my query, please help me find a more appropriate platform to get help for my problem.

**Comment by JonWoodlief** [comment]
Sorry, I don't think my team can help. We pull this data from BSS, but we don't have the tools to interpret this data

Pricing is not a simple get and calculate. you need to know what service, plan, AND deployment region. And what pieces of the pricing info returned are relevant. Teams like VPC or IKS might use their own variables for things.

I would either use the cost estimator, or look for docs on the specific service (VPC for VSI images) to explain how to estimate pricing. Pricing plans from GC are not going to be adequate on their own

**Comment by padamstx** [comment]
@xdevapps I think Jon's advice above about the need to use the cost estimator and/or contact the specific service (VPC) for more detailed info is the best solution we can provide at this point.

**Comment by xdevapps** [comment]
Thank you both for your help. I will look into using the cost estimator and will also consider contacting the VPC teams.
Closing this issue.
