### ISSUE TITLE
Cannot fetch API keys for other users

### ISSUE THREAD

**Issue by nilekell** [IBM/platform-services-python-sdk#236]
I caanot fetch API keys for other users as I am getting ` Error: The specified IAM ID does not match the IAM ID in the token., Code: 400`. This happens when I run the following code:

```
service_client = IamIdentityV1.new_instance()
user_api_keys_response = service_client.list_api_keys(account_id=account_id, iam_id=iam_id, include_history=True).get_result()
```

I presume my error is suggesting that you cannot fetch API keys for users other than the user you are requesting with, as I discovered from the [docs](https://cloud.ibm.com/apidocs/iam-identity-token-api?code=python#list-api-keys) which state: ‘If a service IAM ID is specified in iam_id then account_id must match the account of the IAM ID. If a user IAM ID is specified in iam_id then account_id must match the account of the Authorization token.’.

Is there a way to fetch API keys for other users?
''

**Comment by michaelbeck** [comment]
Only users can fetch their own user API key. Admins however can list the API keys of the account. So basically the above code should work if you don't specify the `iam_id` parameter but specify `scope=account`. You can additionally specify `type=user` to reduce the result to user API keys only.

**Comment by nilekell** [comment]
Ok, thank you for the clarification.
