### ISSUE TITLE
Why does the V2 API call the back end of V3

### ISSUE THREAD

**Issue by emxxjnm** [IBM/platform-services-python-sdk#63]
**Describe the bug**
Why does the V2 API call the back end of V3
https://github.com/IBM/platform-services-python-sdk/blob/master/ibm_platform_services/global_search_v2.py#L168
api docs: https://cloud.ibm.com/apidocs/search#v2-search

**To Reproduce**
List the steps that can be used to demonstrate the bug.  Include the name of the service and operation that you're trying to invoke, if applicable.  Be sure to describe any relevant info regarding parameter values used with your API invocation.

**Expected behavior**

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version 0.15.5
 - Python Version python 3.8
 - GlobalSearchV2
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**
Were you able to avoid the problem by changing your application code slightly?

**Comment by padamstx** [comment]
Hi @emxxjnm, sorry that I'm just getting to this question... 
The `POST /v2/resources/search` operation has been deprecated in favor of the `POST /v3/resources/search` operation.   This change was made within "version 2" of the Search API.  It probably would have been more proper to define a new version 3 of the entire API, but that was not done in this case.
